on: [push, pull_request]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Format main
        run: sudo apt install emacs; bash ./lisp-format src/main.lisp > src/main_from.lisp;
      - name: Compare with format main
        run: diff src/main.lisp src/main_from.lisp;
      - name: Format input
        run: bash ./lisp-format src/input.lisp > src/input_from.lisp;
      - name: Compare with format input
        run: diff src/input.lisp src/input_from.lisp;
      - name: Format line
        run: bash ./lisp-format src/line.lisp > src/line_from.lisp;
      - name: Compare with format line
        run: diff src/line.lisp src/line_from.lisp;
      - name: Format lagrange
        run: bash ./lisp-format src/lagrange.lisp > src/lagrange_from.lisp;
      - name: Compare with format lagrange
        run: diff src/lagrange.lisp src/lagrange_from.lisp;
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup SBCL
        uses: cheeze2000/setup-sbcl@v1
        with:
          version: 2.2.8
      - name: Verify installation
        run: sbcl --non-interactive --eval "(print (ql:client-version))" --eval "(print (asdf:asdf-version))"
      - name: Test
        run: sbcl --script test/test.lisp